#!/usr/bin/env python3
"""Scaffold a HACD Stack issuance project folder so a builder never starts blank.

Creates `project_<ticker>/` containing:
  - launch_spec.json   prefilled from the flags you pass (and the supply math
    computed for you, so it passes the validator's supply equation on first run)
  - the 8 required document files, each stubbed with its template heading and a
    one-line "fill me in" note keyed to SKILL.md

The point: the AI fills the *content*, but the folder, filenames, and the spec
skeleton — the parts that cause ticker mismatches and missing-field errors — are
generated correctly up front.

Examples:
  # Minimal — supply is computed from lots × units:
  python3 scripts/new_project.py --name "StackFire" --ticker SFR \\
      --type FT --lots 100 --units 10000 --cost 50

  # Into a specific parent directory:
  python3 scripts/new_project.py --name "ProofPress" --ticker PRSS \\
      --type HYBRID --lots 500 --units 20000 --cost 50 --out ./submissions

After scaffolding:
  1. Open the folder, hand it (or its launch_spec.json) to the AI with SKILL.md /
     BUILD.md loaded, and let it write the document bodies.
  2. python3 scripts/validate_launch_spec.py project_<ticker>/launch_spec.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ASSET_TYPES = {"FT", "NFT", "SFT", "HYBRID"}

# (filename, H1 heading, one-line note pointing at the SKILL.md template)
# `anchor` docs get the canonical supply numbers embedded so a fresh scaffold
# passes the validator's cross-doc check before the prose is even written.
DOCS = [
    ("incubator_fit_review.md", "Incubator Fit Review",
     "Verdict (Strong/Potential/Weak fit), why it fits HACD, what HACD adds, concerns.", False),
    ("project_profile.md", "Project Profile",
     "One-liner, category, problem, asset concept, why HACD, target users, launch readiness.", False),
    ("stack_design.md", "Stack Design",
     "Asset type, supply table, stack cost, formation rules, participant flow, removal logic.", True),
    ("launchpad_copy.md", "Launchpad Copy",
     "Hero, what it is, why HACD, how Stack works, launch details, utility, FAQ, risk disclosure.", True),
    ("issuer_faq.md", "Issuer FAQ",
     "Do I need HACD? Do I need HAC? Is this an investment? (No — never promise returns.)", False),
    ("x_announcement.md", "X Announcement",
     "1 official + 1 educational + 1 founder post + 1 short thread + 3 alternate hooks.", False),
    ("review_checklist.md", "Review Checklist",
     "Formation logic, copy safety, launch readiness checkboxes (see SKILL.md template).", False),
    ("issuer_intake_form.md", "Issuer Intake Form",
     "The 9-section intake (see templates/issuer_intake_form.md). Fill this first.", False),
]


def build_spec(args: argparse.Namespace) -> dict:
    total_supply = args.lots * args.units
    return {
        "schema_version": "0.1.0",
        "project": {
            "name": args.name,
            "ticker": args.ticker,
            "category": args.category or "",
            "description": args.description or "",
            "website": args.website or "",
            "x": args.x or "",
            "contact": args.contact or "",
        },
        "asset": {
            "type": args.type,
            "total_supply": total_supply,
            "decimals": args.decimals,
            "unit_name": args.unit_name or "",
            "utility_summary": "",
        },
        "stack": {
            "total_hacd_lots": args.lots,
            "hacd_per_lot": 1,
            "units_per_hacd_lot": args.units,
            "stack_cost_hac_per_hacd": args.cost,
            "network_fee_required": True,
            "designated_address_required": False,
            "designated_address": "",
            "first_phase_hacd_lots": 0,
            "public_phase_hacd_lots": args.lots,
            "removal_effect": "burn",
        },
        "launch": {
            "target_date_utc": args.date or "",
            "launchpad_url": "",
            "phase_model": "public",
            "min_hacd_per_participant": 1,
            "max_hacd_per_participant": args.max_per or None,
            "status": "draft",
        },
        "copy": {
            "headline": "",
            "subheadline": "",
            "short_description": args.description or "",
            "risk_disclosure": "",
        },
        "review": {
            "issuer_confirmed": False,
            "hacd_labs_reviewed": False,
            "legal_review_required": True,
            "notes": [
                "Scaffolded by scripts/new_project.py — bodies to be written by the AI.",
            ],
        },
    }


def doc_stub(heading: str, project: str, note: str, anchor: bool, args: argparse.Namespace) -> str:
    body = (
        f"# {heading}: {project}\n\n"
        f"> Stub generated by scripts/new_project.py. Replace this block.\n"
        f"> {note}\n"
        f"> Follow the matching template in SKILL.md exactly. Mark guesses as "
        f"`Needs issuer confirmation`.\n"
    )
    if anchor:
        total = args.lots * args.units
        # Pre-seed the supply numbers the validator cross-checks against the spec,
        # plus the required safety disclosures, so a fresh scaffold is clean.
        body += (
            f"\n## Supply (do not change without updating launch_spec.json)\n\n"
            f"- Total supply: {total:,}\n"
            f"- HACD lots: {args.lots:,}\n"
            f"- Units per HACD lot: {args.units:,}\n"
            f"- Stack cost: {args.cost:g} HAC per HACD\n"
            f"\n## Risk disclosure\n\n"
            f"This is not financial advice and not an investment product. "
            f"Stack cost is a formation reference, not a guaranteed floor or price. "
            f"Final Launchpad parameters must be verified by HACD Labs.\n"
        )
    return body


def main() -> None:
    p = argparse.ArgumentParser(description="Scaffold a HACD Stack issuance project folder.")
    p.add_argument("--name", required=True, help="Project name, e.g. 'StackFire'")
    p.add_argument("--ticker", required=True, help="Asset symbol, e.g. SFR")
    p.add_argument("--type", required=True, choices=sorted(ASSET_TYPES), help="Asset type")
    p.add_argument("--lots", required=True, type=int, help="Number of HACD lots")
    p.add_argument("--units", required=True, type=int, help="Units formed per HACD lot")
    p.add_argument("--cost", required=True, type=float, help="Stack cost in HAC per HACD")
    p.add_argument("--category", default="", help="meme/AI agent/art/RWA/community/utility/...")
    p.add_argument("--description", default="", help="One-sentence description")
    p.add_argument("--website", default="")
    p.add_argument("--x", default="", help="X / community link")
    p.add_argument("--contact", default="")
    p.add_argument("--decimals", type=int, default=0, help="0 for indivisible units")
    p.add_argument("--unit-name", dest="unit_name", default="")
    p.add_argument("--date", default="", help="Target launch date (UTC)")
    p.add_argument("--max-per", dest="max_per", type=int, default=0,
                   help="Max HACD per participant (0 = no cap)")
    p.add_argument("--out", default=".", help="Parent directory for the project folder")
    p.add_argument("--force", action="store_true", help="Overwrite an existing folder")
    args = p.parse_args()

    if args.lots <= 0 or args.units <= 0 or args.cost < 0:
        print("ERROR: --lots and --units must be positive; --cost must be >= 0")
        sys.exit(1)

    folder = Path(args.out) / f"project_{args.ticker.lower()}"
    if folder.exists() and not args.force:
        print(f"ERROR: {folder} already exists. Use --force to overwrite.")
        sys.exit(1)
    folder.mkdir(parents=True, exist_ok=True)

    spec = build_spec(args)
    spec_path = folder / "launch_spec.json"
    spec_path.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")

    for fname, heading, note, anchor in DOCS:
        (folder / fname).write_text(
            doc_stub(heading, args.name, note, anchor, args), encoding="utf-8"
        )

    total = args.lots * args.units
    cost = args.lots * args.cost
    print(f"OK: scaffolded {folder}/")
    print(f"  launch_spec.json + {len(DOCS)} document stubs")
    print(f"  total_supply = {args.lots:,} lots x {args.units:,} units = {total:,}")
    print(f"  formation cost reference = {cost:,} HAC + network fees")
    print()
    print("Next:")
    print(f"  1. Load SKILL.md (or BUILD.md) in your AI and have it fill the document bodies.")
    print(f"  2. python3 scripts/validate_launch_spec.py {spec_path}")


if __name__ == "__main__":
    main()
